# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_checkout', '0002_auto_20161231_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
