# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_checkout', '0003_mandate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.CharField(max_length=12),
        ),
    ]
