# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_checkout', '0004_auto_20161231_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
